# Generated by Django 3.2.9 on 2021-11-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BPBackendDjango', '0002_auto_20211116_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='o_auth_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_time',
        ),
    ]
